blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://code.hannahvernon.com/hannah-vernon/tayler-log-tailer/src/branch/main/README.md
    about: Read the README for usage and configuration details.
