name: Feature request
description: Suggest an idea for Tayler Log Tailer
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / use case
      description: What problem are you trying to solve? What is the use case?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the behavior or feature you would like.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or features you have considered.
    validations:
      required: false
